import 'package:gkfit/provider/nutrition_search_provider.dart';
import 'package:gkfit/model/trackers/Nutrition_database_model.dart';

class NutritionSearchRepository {
  NutritionSearchProvider _nutritionApiProvider = NutritionSearchProvider();

  Future<List<NutritionDatabaseModel>> searchByName(searchTerm) async {
    String body = await _nutritionApiProvider.DoSearch(searchTerm);
    return AutogeneratedNutritionDatabase.fromJsonString(body).results;
  }
}
