import 'package:equatable/equatable.dart';

class CalorieIntakeModel extends Equatable {
  final String quantity_in_ml;
  final String day;

  CalorieIntakeModel(this.quantity_in_ml, this.day);

  @override
  List<Object> get props => [quantity_in_ml, day];

  factory CalorieIntakeModel.fromJson(Map<String, dynamic> json) {
    return CalorieIntakeModel(json['quantity_in_ml'] , json['day']);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['quantity_in_ml'] = quantity_in_ml;
    data['day'] = day;
    return data;
  }
  
}


class AutogeneratedWaterIntake {
  final List<CalorieIntakeModel> results;

  AutogeneratedWaterIntake({this.results});

  factory AutogeneratedWaterIntake.fromJson(Map<String, dynamic> json) {
    List<CalorieIntakeModel> temp;
    if (json['results'] != null) {
      temp = <CalorieIntakeModel>[];
      json['results'].forEach((v) {
        temp.add(CalorieIntakeModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedWaterIntake(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
