import 'package:equatable/equatable.dart';

class AutogeneratedWeightTracker {
  final List<WeightTrackerModel> results;

  AutogeneratedWeightTracker({this.results});

  factory AutogeneratedWeightTracker.fromJson(Map<String, dynamic> json) {
    List<WeightTrackerModel> temp;
    if (json['results'] != null) {
      temp = <WeightTrackerModel>[];
      json['results'].forEach((v) {
        temp.add(WeightTrackerModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedWeightTracker(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class WeightTrackerModel extends Equatable {
  final String time;
  final double weight_in_kgs, height_in_cm, bmi, bodyfat;

  WeightTrackerModel(
      {this.time,
      this.weight_in_kgs,
      this.height_in_cm,
      this.bmi,
      this.bodyfat});

  @override
  List<Object> get props => [time, weight_in_kgs, height_in_cm, bmi, bodyfat];

  factory WeightTrackerModel.fromJson(Map<String, dynamic> _json) {
    return WeightTrackerModel(
        time: _json['time'],
        weight_in_kgs: double.parse(_json['weight_in_kgs'].toString()),
        height_in_cm: double.parse(_json['height_in_cm'].toString()),
        bmi: double.parse(_json['bmi'].toString()),
        bodyfat:double.parse( _json['bodyfat'].toString()));
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['time'] = time;
    data['weight_in_kgs'] = weight_in_kgs;
    data['height_in_cm'] = height_in_cm;
    data['bmi'] = bmi;
    data['bodyfat'] = bodyfat;
    return data;
  }
}
