import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_model.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_repository.dart';
import 'package:gkfit/screens/dashboard/home/trackers/water_tracker/history/models/balance.dart';
import 'package:gkfit/services/auth_service.dart';
import 'package:gkfit/widgets/charts/time_series_chart_with_bar_renderer.dart';
import 'package:provider/provider.dart';
import 'package:charts_flutter/flutter.dart' as charts;
class WaterIntakeHistoryWidget extends StatefulWidget {
  WaterIntakeHistoryWidget({Key key}) : super(key: key);

  @override
  _WaterIntakeHistoryWidgetState createState() =>
      _WaterIntakeHistoryWidgetState();
}

class _WaterIntakeHistoryWidgetState extends State<WaterIntakeHistoryWidget> {
  WaterIntakeRepository _waterIntakeRepository = WaterIntakeRepository();
  User user;
  List<charts.Series<Balance, String>> series;
  @override
  void initState() {
    // TODO: implement initState
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    user = Provider.of<User>(context);
    return Container(
        height: 200,
        child: Padding(
          padding: const EdgeInsets.all(16.0),
          child: FutureBuilder<List<charts.Series<TimeSeriesSales, DateTime>>>(
            future: _createWaterIntakeChart(),
            builder: (BuildContext context,
                AsyncSnapshot<List<charts.Series<TimeSeriesSales, DateTime>>>
                    snapshot) {
              
              if (snapshot.hasData) {
                
                return new TimeSeriesBar(
                  snapshot.data,
                  animate: true,
                );
              }
              return Center(
                child: CircularProgressIndicator(),
              );
            },
          ),
        ));
  }

  Future<List<charts.Series<TimeSeriesSales, DateTime>>>
      _createWaterIntakeChart() async {
    AutogeneratedWaterIntake autogen =
        await _waterIntakeRepository.fetchWaterIntakeHistory(user.uid);
    List<TimeSeriesSales> data = [];
    autogen.results.forEach((element) {

      data.add(new TimeSeriesSales(DateTime.parse(element.day).toLocal(),
          int.parse(element.quantity_in_ml).toInt()));
    });

    return [
      new charts.Series<TimeSeriesSales, DateTime>(
        id: 'Sales',
        colorFn: (_, __) => charts.MaterialPalette.blue.shadeDefault,
        domainFn: (TimeSeriesSales sales, _) =>
            new DateTime(sales.time.year, sales.time.month, sales.time.day),
        measureFn: (TimeSeriesSales sales, _) => sales.sales,
        data: data,
      )
    ];
  }
}
