import 'package:gkfit/bloc/trackers/water_intake/water_intake_bloc.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:gkfit/bloc/authentication/authentication_bloc.dart';

import 'package:gkfit/bloc/trackers/water_intake/water_intake_model.dart';
import 'package:flutter/material.dart';
import 'package:flutter/widgets.dart';
import 'package:gkfit/screens/dashboard/home/trackers/water_tracker/water_intake_history/waterIntakeHistoryWidget.dart';
import 'package:gkfit/screens/dashboard/ui_view/glass_view.dart';

import '../../../dashboard_theme.dart';
import './mini_water_intake_dashboard.dart';
import 'history/group_chart.dart';
import 'history/history_widget.dart';
import './history/database.dart' as db;
import 'package:charts_flutter/flutter.dart' as charts;
import './history/models/balance.dart';
import 'package:provider/provider.dart';
import 'dart:async';
import './../../../ui_view/title_view.dart';
import 'history/models/domain.dart';

import 'package:gkfit/widgets/ui/blog_list_loader.dart';
import 'package:charts_flutter/flutter.dart' as charts;
import 'package:gkfit/widgets/charts/time_series_chart_with_bar_renderer.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_model.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_repository.dart';
import 'package:firebase_auth/firebase_auth.dart';
class WaterTrackerHomeScreen extends StatefulWidget {
  @override
  State<StatefulWidget> createState() => WaterTrackerHomeScreenState();
}

class WaterTrackerHomeScreenState extends State<WaterTrackerHomeScreen> {
  WaterIntakeBloc waterIntakebloc;
  FirebaseUser  user;

  WaterIntakeRepository _waterIntakeRepository = WaterIntakeRepository();
  List<charts.Series<Balance, String>> series;

  @override
  void initState() {
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    user = BlocProvider.of<AuthenticationBloc>(context).state.user;
    waterIntakebloc = BlocProvider.of<WaterIntakeBloc>(context);
    // TODO: implement build
    return WillPopScope(
      onWillPop: _willPopCallback,
      child: Scaffold(
        appBar: AppBar(
          elevation: 10,
          leading: new IconButton(
              icon: new Icon(Icons.arrow_back),
              onPressed: () {
                // waterIntakebloc..add(UpdateWaterIntakeEvent());
                Navigator.pop(context, true);
              }),
          iconTheme: IconThemeData(color: Colors.black),
          backgroundColor: DashboardTheme.nearlyWhite,
          shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.only(
            bottomLeft: Radius.circular(45),
            bottomRight: Radius.circular(45),
          )),
          centerTitle: true,
          title: Text(
            "Water Tracker",
            style: Theme.of(context)
                .textTheme
                .headline6
                .copyWith(color: Colors.black),
          ),
        ),
        backgroundColor: DashboardTheme.background,
        body: FutureBuilder(
          future: _createWaterIntakeChart(),
          builder: (BuildContext context, AsyncSnapshot snapshot) {
            if (snapshot.hasData) {
              return listView(context, snapshot.data);
            }

            return BlogLisLoader(
              length: 3,
            );
          },
        ),
      ),
    );
  }

  Widget listView(
      BuildContext context, List<charts.Series<dynamic, DateTime>> data) {
    waterIntakebloc = BlocProvider.of<WaterIntakeBloc>(context);
    int count = 7;
    List<Widget> listViews = <Widget>[];
    listViews.add(WaterIntakeMiniDashboardView());
    listViews.add(
      GlassView(),
    );

    listViews
        .add(JustTitleViewWithoutAnimation(titleTxt: "Water Intake Chart"));

    listViews.add(WaterIntakeHistoryWidget(
      data: data,
    ));
    return ListView.builder(
        padding: EdgeInsets.only(
          bottom: 62 + MediaQuery.of(context).padding.bottom,
        ),
        itemCount: listViews.length,
        scrollDirection: Axis.vertical,
        itemBuilder: (BuildContext context, int index) {
          return listViews[index];
        });
  }

  Future<List<charts.Series<TimeSeriesSales, DateTime>>>
      _createWaterIntakeChart() async {
    AutogeneratedWaterIntake autogen =
        await _waterIntakeRepository.fetchWaterIntakeHistory(user.uid);
    List<TimeSeriesSales> data = [];
    autogen.results.forEach((element) {
      if (DateTime.parse(element.day).toLocal().day ==
          DateTime.parse(waterIntakebloc.state.getDay()).toLocal().day) {
        data.add(new TimeSeriesSales(DateTime.parse(element.day).toLocal(),
            waterIntakebloc.state.getCurrentQuantityInMl()));
      } else {
        data.add(new TimeSeriesSales(DateTime.parse(element.day).toLocal(),
            int.parse(element.quantity_in_ml).toInt()));
      }
    });

    return [
      new charts.Series<TimeSeriesSales, DateTime>(
        id: 'Sales',
        colorFn: (_, __) => charts.MaterialPalette.blue.shadeDefault,
        domainFn: (TimeSeriesSales sales, _) =>
            new DateTime(sales.time.year, sales.time.month, sales.time.day),
        measureFn: (TimeSeriesSales sales, _) => sales.sales,
        data: data,
      )
    ];
  }

  Future<bool> _willPopCallback() async {
    // await showDialog or Show add banners or whatever
    // then
    // waterIntakebloc..add(UpdateWaterIntakeEvent());
    return true; // return true if the route to be popped
  }
}
