import 'package:equatable/equatable.dart';
import 'dart:convert';

class AutogeneratedNutritionDatabase {
  final List<NutritionDatabaseModel> results;

  AutogeneratedNutritionDatabase({this.results});
  factory AutogeneratedNutritionDatabase.fromJsonString(String json_string) {
    return AutogeneratedNutritionDatabase.fromJson(jsonDecode(json_string));
  }
  factory AutogeneratedNutritionDatabase.fromJson(Map<String, dynamic> json) {
    List<NutritionDatabaseModel> temp;
    if (json['results'] != null) {
      temp = <NutritionDatabaseModel>[];
      json['results'].forEach((v) {
        temp.add(NutritionDatabaseModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedNutritionDatabase(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class NutritionDatabaseModelList {
  final List<NutritionDatabaseModel> nutritionDatabaseModelList;
  NutritionDatabaseModelList({this.nutritionDatabaseModelList});
  factory NutritionDatabaseModelList.fromList(List<dynamic> _list) {
    List<NutritionDatabaseModel> temp =[];

    _list.forEach((element) {
      element = json.decode(element);
      temp.add(
        NutritionDatabaseModel.fromJson(element) 
       // NutritionDatabaseModel(element._id, element.name, element.proteins_in_grams, element.fat_in_grams, element.fibers_in_grams, element.carbs_in_grams, element.total_calories, element.quantity_in_grams)
      );
    });
    return NutritionDatabaseModelList(nutritionDatabaseModelList: temp);
  }
}

class NutritionDatabaseModel extends Equatable {
  final String _id;
  final String name;
  final double proteins_in_grams,
      fat_in_grams,
      fibers_in_grams,
      carbs_in_grams,
      total_calories,
      quantity_in_grams;

  NutritionDatabaseModel(
      this._id,
      this.name,
      this.proteins_in_grams,
      this.fat_in_grams,
      this.fibers_in_grams,
      this.carbs_in_grams,
      this.total_calories,
      this.quantity_in_grams);

  @override
  List<Object> get props => [
        _id,
        name,
        proteins_in_grams,
        fat_in_grams,
        fibers_in_grams,
        carbs_in_grams,
        total_calories,
        quantity_in_grams
      ];

  factory NutritionDatabaseModel.fromJson(Map<String, dynamic> json) {
    print(double.parse((json['proteins_in_grams']).toString()));
    return NutritionDatabaseModel(
        json['_id'] as String,
        json['name'] as String,
        double.parse(json['proteins_in_grams'].toString()),
        double.parse(json['fat_in_grams'].toString()),
        double.parse(json['fibers_in_grams'].toString()),
        double.parse(json['carbs_in_grams'].toString()),
        double.parse(json['total_calories'].toString()),
        double.parse(json['quantity_in_grams'].toString()));
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['_id'] = _id;
    data['name'] = name;
    data['proteins_in_grams'] = proteins_in_grams;
    data['fat_in_grams'] = fat_in_grams;
    data['fibers_in_grams'] = fibers_in_grams;
    data['carbs_in_grams'] = carbs_in_grams;
    data['total_calories'] = total_calories;
    data['quantity_in_grams'] = quantity_in_grams;
    return data;
  }
}
