import 'package:equatable/equatable.dart';

/// generate by https://javiercbk.github.io/json_to_dart/
class AutogeneratedWaterIntake {
  final List<WaterIntakeModel> results;

  AutogeneratedWaterIntake({this.results});

  factory AutogeneratedWaterIntake.fromJson(Map<String, dynamic> json) {
    List<WaterIntakeModel> temp;
    if (json['results'] != null) {
      temp = <WaterIntakeModel>[];
      json['results'].forEach((v) {
        temp.add(WaterIntakeModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedWaterIntake(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class WaterIntakeModel extends Equatable {
  final String quantity_in_ml;
  final String day;
  final String last_drink;

  WaterIntakeModel(this.quantity_in_ml, this.day,this.last_drink);

  @override
  List<Object> get props => [quantity_in_ml, day];

  factory WaterIntakeModel.fromJson(Map<String, dynamic> json) {
    return WaterIntakeModel(json['quantity_in_ml'] , json['day'],json['last_drink']);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['quantity_in_ml'] = quantity_in_ml;
    data['day'] = day;
    data['last_drink'] = last_drink;
    return data;
  }
  
}
