import 'dart:async';

import 'package:gkfit/bloc/trackers/water_intake/water_intake_model.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_provider.dart';


class WaterIntakeRepository {
  static String baseUrl =  "https://trackers-api-dot-hygieafit.el.r.appspot.com/trackers/v1/water";
  final WaterIntakeProvider _waterIntakeProvider = WaterIntakeProvider(waterIntakeProvideBaseurl: baseUrl);

Future<dynamic> updateDailyWaterIntake(uid, day, quantity_in_ml) => _waterIntakeProvider.addWaterIntakeLog(uid, day, quantity_in_ml);
Future<AutogeneratedWaterIntake> getWaterIntakeData(uid, start_day, end_day) => _waterIntakeProvider.getWaterIntakeData(uid, start_day, end_day);
Future<AutogeneratedWaterIntake> fetchWaterIntake(uid, day) => _waterIntakeProvider.fetchWaterIntake(uid, day);
}