import 'dart:async';
import 'dart:developer' as developer;

import 'package:bloc/bloc.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_model.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_repository.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_state.dart';
import 'package:equatable/equatable.dart';
import 'package:intl/intl.dart';
import 'package:rxdart/rxdart.dart';

class WaterIntakeEvent extends Equatable {
  @override

  List<Object> get props => throw UnimplementedError();
}

class UpdateWaterIntakeEvent extends WaterIntakeEvent {}

class FetchWaterIntakeEvent extends WaterIntakeEvent {}

class AddtwoFiftyMlevent extends WaterIntakeEvent {}

class SubtracttwoFiftyMlevent extends WaterIntakeEvent {}

class AddLastDrinkDataEvent extends WaterIntakeEvent {}

class WaterIntakeBloc extends Bloc<WaterIntakeEvent, WaterIntakeState> {
  String uid;

  WaterIntakeBloc({this.uid});
  WaterIntakeRepository _waterIntakeRepository = WaterIntakeRepository();

  dispose() {
    super.close();
  }

  @override
  WaterIntakeState get initialState => UnWaterIntakeState(0);

  @override
  Stream<WaterIntakeState> mapEventToState(
    WaterIntakeEvent event,
  ) async* {
    final currentState = state;
    try {
      if (event is AddLastDrinkDataEvent) {
        print('update last drink');
        var timeformatter = new DateFormat('Hm');
        String lastWaterIntake = timeformatter.format(DateTime.now());

        yield InWaterIntakeState(currentState.version,
            currentState.getCurrentQuantityInMl(), currentState.getDay(), lastWaterIntake)
            .copyWith(currentState.getCurrentQuantityInMl(),  currentState.getDay(), lastWaterIntake);
        ;
      }

      if (event is AddtwoFiftyMlevent) {
        var update_value = (currentState.getCurrentQuantityInMl() + 250 > 3500)
            ? 3800
            : currentState.getCurrentQuantityInMl() + 250;
        yield InWaterIntakeState(currentState.version + 1, update_value,
            DateTime(DateTime.now().day).toIso8601String(),currentState.getLastWaterIntake());
      }
      if (event is SubtracttwoFiftyMlevent) {
        var update_value = (currentState.getCurrentQuantityInMl() - 250 < 0)
            ? 0
            : currentState.getCurrentQuantityInMl() - 250;
        yield InWaterIntakeState(currentState.version + 1, update_value,
            DateTime(DateTime.now().day).toIso8601String(),currentState.getLastWaterIntake());
      }
      if (event is UpdateWaterIntakeEvent) {
        await _waterIntakeRepository.updateDailyWaterIntake(
            uid,
            DateTime(DateTime.now().day).toIso8601String(),
            currentState.getCurrentQuantityInMl());
        yield InWaterIntakeState(
            currentState.version + 1,
            currentState.getCurrentQuantityInMl(),
            DateTime(DateTime.now().day).toIso8601String(),
            currentState.getLastWaterIntake());
      }
      if (event is FetchWaterIntakeEvent) {
        AutogeneratedWaterIntake result =
            await _waterIntakeRepository.fetchWaterIntake(
                uid, DateTime(DateTime.now().day).toIso8601String());

        yield InWaterIntakeState(currentState.version + 1,
            (result.results.length > 0) ? int.parse(result.results[0].quantity_in_ml) : 0,(result.results.length > 0) ? result.results[0].day : DateTime(DateTime.now().day).toIso8601String()
            ,currentState.getLastWaterIntake());
      }
    } catch (_, stackTrace) {
      developer.log('$_',
          name: 'WaterIntakeBloc', error: _, stackTrace: stackTrace);
      yield state;
    }
  }
}
