import 'dart:async';
import 'dart:developer' as developer;

import 'package:bloc/bloc.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_model.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_repository.dart';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_state.dart';
import 'package:equatable/equatable.dart';
import 'package:gkfit/model/userPreferenceModel.dart';
import 'package:intl/intl.dart';
import 'package:rxdart/rxdart.dart';
import 'package:shared_preferences/shared_preferences.dart';

class WaterIntakeEvent extends Equatable {
  @override
  List<Object> get props => throw UnimplementedError();
}

class UpdateWaterIntakeEvent extends WaterIntakeEvent {}

class FetchWaterIntakeEvent extends WaterIntakeEvent {}

class AddtwoFiftyMlevent extends WaterIntakeEvent {}

class SubtracttwoFiftyMlevent extends WaterIntakeEvent {}

class AddLastDrinkDataEvent extends WaterIntakeEvent {}

class WaterIntakeBloc extends Bloc<WaterIntakeEvent, WaterIntakeState> {
  String uid;

  WaterIntakeBloc({this.uid});
  WaterIntakeRepository _waterIntakeRepository = WaterIntakeRepository();

  @override
  Future<void> close() {
    // TODO: implement close
    return super.close();
  }

  @override
  WaterIntakeState get initialState => UnWaterIntakeState(0);

  @override
  Stream<WaterIntakeState> mapEventToState(
    WaterIntakeEvent event,
  ) async* {
    final currentState = state;
    try {
      if (event is AddLastDrinkDataEvent &&
          currentState is InWaterIntakeState) {
        var timeformatter = new DateFormat('hh:mm a');
        String lastWaterIntake = timeformatter.format(DateTime.now().toLocal());
        developer.log(
          ' Add last drink event  ',
          name: 'WaterIntakeBloc',
        );

        yield currentState.copyWith(currentState.getCurrentQuantityInMl(),
            currentState.getDay(), lastWaterIntake);
        ;
      }

      if (event is AddtwoFiftyMlevent) {
        var update_value = (currentState.getCurrentQuantityInMl() + 250 >
                UserPreferenceModel().daily_water_intake_target)
            ? UserPreferenceModel().daily_water_intake_target
            : currentState.getCurrentQuantityInMl() + 250;
        yield InWaterIntakeState(
            currentState.version + 1,
            update_value,
            DateTime(DateTime.now().year, DateTime.now().month,
                    DateTime.now().day)
                .toUtc()
                .toIso8601String(),
            currentState.getLastWaterIntake());
      }
      if (event is SubtracttwoFiftyMlevent) {
        var update_value = (currentState.getCurrentQuantityInMl() - 250 < 0)
            ? 0
            : currentState.getCurrentQuantityInMl() - 250;
        yield InWaterIntakeState(
            currentState.version + 1,
            update_value,
            DateTime(DateTime.now().year, DateTime.now().month,
                    DateTime.now().day)
                .toUtc()
                .toIso8601String(),
            currentState.getLastWaterIntake());
      }
      if (event is UpdateWaterIntakeEvent) {
        developer.log(
          ' updating Water quantity',
          name: 'WaterIntakeBloc',
        );
        yield LoadingWaterIntakeState(
            currentState.version,
            currentState.getCurrentQuantityInMl(),
            currentState.getDay(),
            currentState.getLastWaterIntake());
        _waterIntakeRepository.updateDailyWaterIntake(
            uid,
            DateTime(DateTime.now().year, DateTime.now().month,
                    DateTime.now().day)
                .toUtc()
                .toIso8601String(),
            currentState.getCurrentQuantityInMl(),
            currentState.getLastWaterIntake());
        developer.log(
          ' updated Water quantity',
          name: 'WaterIntakeBloc',
        );
        yield currentState;
      }
      if (event is FetchWaterIntakeEvent) {
        yield LoadingWaterIntakeState(
            currentState.version,
            currentState.getCurrentQuantityInMl(),
            currentState.getDay(),
            currentState.getLastWaterIntake());
        if (currentState is UnWaterIntakeState) {
          AutogeneratedWaterIntake result =
              await _waterIntakeRepository.fetchWaterIntake(
                  uid,
                  DateTime(DateTime.now().year, DateTime.now().month,
                          DateTime.now().day)
                      .toUtc()
                      .toIso8601String());

          yield InWaterIntakeState(
              currentState.version + 1,
              (result.results.length > 0)
                  ? int.parse(result.results[0].quantity_in_ml)
                  : 0,
              DateTime(DateTime.now().year, DateTime.now().month,
                      DateTime.now().day)
                  .toUtc()
                  .toIso8601String(),
              (result.results.length > 0) ? result.results[0].last_drink ?? '' : '');
        } else if (currentState is InWaterIntakeState) {
          final lastMidnight = DateTime(
                  DateTime.now().year, DateTime.now().month, DateTime.now().day)
              .toLocal();
          developer.log(
            ' Fetch Water Intake  ' +
                DateTime.parse(currentState.getDay()).toLocal().day.toString(),
            name: 'WaterIntakeBloc',
          );

          if (DateTime.parse(currentState.getDay()).toLocal().day !=
              lastMidnight.day) {
            developer.log(
              ' Resetting the day',
              name: 'WaterIntakeBloc',
            );
            yield currentState.copyWith(
                0, lastMidnight.toUtc().toIso8601String(), 'not today');
          } else {
            AutogeneratedWaterIntake result =
                await _waterIntakeRepository.fetchWaterIntake(
                    uid,
                    DateTime(DateTime.now().year, DateTime.now().month,
                            DateTime.now().day)
                        .toUtc()
                        .toIso8601String());
            yield     InWaterIntakeState(
              currentState.version + 1,
              (result.results.length > 0)
                  ? int.parse(result.results[0].quantity_in_ml)
                  : 0,
              DateTime(DateTime.now().year, DateTime.now().month,
                      DateTime.now().day)
                  .toUtc()
                  .toIso8601String(),
              (result.results.length > 0) ? result.results[0].last_drink ?? '' : '');
          }
        }
      }
    } catch (_, stackTrace) {
      developer.log('$_',
          name: 'WaterIntakeBloc', error: _, stackTrace: stackTrace);
      yield currentState;
    }
  }
}
