import 'dart:async';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:gkfit/bloc/trackers/water_intake/water_intake_model.dart';

class WaterIntakeProvider {
  String waterIntakeProvideBaseurl;
  WaterIntakeProvider({this.waterIntakeProvideBaseurl});
  Future<dynamic> addWaterIntakeLog(uid, day, quantity_in_ml,last_drink) {
    return http.post(waterIntakeProvideBaseurl + '/add/$uid', body: {
      'day': day.toString(),
      'quantity_in_ml': quantity_in_ml.toString(),
      'last_drink': last_drink.toString()
    });
  }

  Future<AutogeneratedWaterIntake> fetchWaterIntake(uid, day) async {
    http.Response results = await http.post(
        waterIntakeProvideBaseurl + '/fetch/$uid',
        body: {"day": day.toString()});
    return AutogeneratedWaterIntake.fromJson(json.decode(results.body));
  }

  Future<AutogeneratedWaterIntake> getWaterIntakeData(
      uid, start_day, end_day) async {
    http.Response results = await http.get(waterIntakeProvideBaseurl +
        '/get/$uid?start_day=$start_day&end_day=$end_day');
    return AutogeneratedWaterIntake.fromJson(json.decode(results.body));
  }

  Future<AutogeneratedWaterIntake> fetchWaterIntakeHistory(uid) async {
    http.Response results =
        await http.get(waterIntakeProvideBaseurl + '/get/$uid/all');
    return AutogeneratedWaterIntake.fromJson(json.decode(results.body));
  }
}
