import 'breakfastModel.dart';
import 'lunchModel.dart';
import 'morningSnackModel.dart';
import 'eveningSnackNodel.dart';
import 'dinnerModel.dart';
import 'dart:convert';
import 'dart:developer' as developer;
import 'package:equatable/equatable.dart' show Equatable;

class EntireDayMealModel extends Equatable {
  String date;
  BreakFastModel breakfast;
  MorningSnackModel morning_snack;
  LunchModel lunch;
  EveningSnackModel evening_snack;
  DinnerModel dinner;
  EntireDayMealModel(
      {this.date,
      this.breakfast,
      this.morning_snack,
      this.lunch,
      this.evening_snack,
      this.dinner}) {}

  factory EntireDayMealModel.emptyModel() {
    return EntireDayMealModel(
        date: DateTime(DateTime.now().day).toIso8601String(),
        breakfast: BreakFastModel(
            calories_list: [],
            meal_list: [],
            quantities_in_grams: [],
            total_calories: 0),
        lunch: LunchModel(
            calories_list: [],
            meal_list: [],
            quantities_in_grams: [],
            total_calories: 0),
        morning_snack: MorningSnackModel(
            calories_list: [],
            meal_list: [],
            quantities_in_grams: [],
            total_calories: 0),
        evening_snack: EveningSnackModel(
            calories_list: [],
            meal_list: [],
            quantities_in_grams: [],
            total_calories: 0),
        dinner: DinnerModel(
            calories_list: [],
            meal_list: [],
            quantities_in_grams: [],
            total_calories: 0));
  }
// factory EntireDayMealModel.fromIndividualMeals (
//   String date,
//   BreakFastModel breakfast,
//   MorningSnackModel morningSnack,
//   LunchModel lunch,
//   EveningSnackModel eveningSnack,
//   DinnerModel dinner
// ) {
//       return EntireDayMealModel(
//         date: date,
//         breakfast: breakfast,
//         morning_snack: morning_snack,
//         lunch: lunch,
//         evening_snack: evening_snack,
//         dinner: dinner);
//   }
// }
  factory EntireDayMealModel.fromJson(Map<String, dynamic> _json) {
    return EntireDayMealModel(
        date: (_json['date'] != null)
            ? _json['date']
            : DateTime(DateTime.now().day).toIso8601String(),
        breakfast: (_json['breakfast'] != null)
            ? BreakFastModel.fromJson(_json['breakfast'])
            : BreakFastModel(
                calories_list: [],
                meal_list: [],
                quantities_in_grams: [],
                total_calories: 0),
        morning_snack: (_json['morning_snack'] != null)
            ? MorningSnackModel.fromJson(_json['morning_snack'])
            : MorningSnackModel(
                calories_list: [],
                meal_list: [],
                quantities_in_grams: [],
                total_calories: 0),
        lunch: (_json['lunch'] != null)
            ? LunchModel.fromJson(_json['lunch'])
            : LunchModel(
                calories_list: [],
                meal_list: [],
                quantities_in_grams: [],
                total_calories: 0),
        evening_snack: (_json['evening_snack'] != null)
            ? EveningSnackModel.fromJson(_json['evening_snack'])
            : EveningSnackModel(
                calories_list: [],
                meal_list: [],
                quantities_in_grams: [],
                total_calories: 0),
        dinner: (_json['dinner'] != null)
            ? DinnerModel.fromJson(_json['dinner'])
            : DinnerModel(
                calories_list: [],
                meal_list: [],
                quantities_in_grams: [],
                total_calories: 0));
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'date': date,
      'breakfast': breakfast,
      'morning_snack': morning_snack,
      'lunch': lunch,
      'evening_snack': evening_snack,
      'dinner': dinner
    };
  }

  String getToday() => DateTime(DateTime.now().day).toIso8601String();

  @override
  // TODO: implement props
  List<Object> get props => [
        this.date,
        this.breakfast,
        this.morning_snack,
        this.lunch,
        this.evening_snack,
        this.dinner
      ];
}

class AutogeneratedEntireDayMeal {
  final List<EntireDayMealModel> results;

  AutogeneratedEntireDayMeal({this.results});

  factory AutogeneratedEntireDayMeal.fromJson(Map<String, dynamic> json) {
    List<EntireDayMealModel> temp;
    if (json['results'] != null) {
      temp = <EntireDayMealModel>[];
      json['results'].forEach((v) {
        temp.add(EntireDayMealModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedEntireDayMeal(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
