import 'package:gkfit/model/trackers/Nutrition_database_model.dart';
import 'dart:convert';
import 'package:equatable/equatable.dart' show Equatable;
class MorningSnackModel extends Equatable  {
  List<NutritionDatabaseModel> meal_list = [];
  List<double> calories_list = [];
  List<double> quantities_in_grams = [];
  double total_calories = 0;
  MorningSnackModel(
      {this.meal_list,
      this.calories_list,
      this.quantities_in_grams,
      this.total_calories});

  factory MorningSnackModel.fromJson(Map<String, dynamic> _json) {
   
    _json['calories_list'] = _json.containsKey('calories_list') ? _json['calories_list'] : [];
    _json['quantities_in_grams'] =_json.containsKey('quantities_in_grams') ? _json['quantities_in_grams'] : [];
    _json['meal_list'] =_json.containsKey('meal_list') ? _json['meal_list'] : [];
    _json['total_calories'] =_json.containsKey('total_calories') ? _json['total_calories'] : double.parse('0');
    List<NutritionDatabaseModel> tempNutritionDattaList =
        List<NutritionDatabaseModel>();
    List<double> tempCaloriesList = List<double>();
    List<double> tempquantities = List<double>();

    _json['meal_list'].forEach((element) {
      element = json.decode(element);
      tempNutritionDattaList.add(NutritionDatabaseModel.fromJson(element)
          // NutritionDatabaseModel(element._id, element.name, element.proteins_in_grams, element.fat_in_grams, element.fibers_in_grams, element.carbs_in_grams, element.total_calories, element.quantity_in_grams)
          );
    });
    _json['calories_list'].forEach((element) {
      tempCaloriesList.add(element.toDouble());
    });
    _json['quantities_in_grams'].forEach((element) {
      tempquantities.add(element.toDouble());
    });

    return MorningSnackModel(
        meal_list: tempNutritionDattaList,
        calories_list: tempCaloriesList,
        quantities_in_grams: tempquantities,
        total_calories: _json['total_calories'].toDouble());
  }

  Map<String, dynamic> toJson() {
    return <String, dynamic>{
      'meal_list': meal_list,
      'calories_list': calories_list,
      'quantities_in_grams': quantities_in_grams,
      'total_calories': total_calories
    };
  }

  List<String> get mealStringList {
    List<String> tempList = [];

    for (NutritionDatabaseModel meal in meal_list) {
      tempList.add(meal.name);
    }
    return tempList;
  }

  double get totalCarbsInGrams {
    double temp = 0;
    if (meal_list.length == 0) {
      return temp;
    } else {
      for (NutritionDatabaseModel meal in meal_list) {
        temp = temp + meal.carbs_in_grams;
      }
      return temp;
    }
  }

  double get totalFatInGrams {
    double temp = 0;
    if (meal_list.length == 0) {
      return temp;
    } else {
      for (NutritionDatabaseModel meal in meal_list) {
        temp = temp + meal.fat_in_grams;
      }
      return temp;
    }
  }

  double get totalFibresInGrams {
    double temp = 0;
    if (meal_list.length == 0) {
      return temp;
    } else {
      for (NutritionDatabaseModel meal in meal_list) {
        temp = temp + meal.fibers_in_grams;
      }
      return temp;
    }
  }

  double get totalproteinsInGrams {
    double temp = 0;
    if (meal_list.length == 0) {
      return temp;
    } else {
      for (NutritionDatabaseModel meal in meal_list) {
        temp = temp + meal.proteins_in_grams;
      }
      return temp;
    }
  }

  @override
  // TODO: implement props
  List<Object> get props => [
    this.meal_list,
      this.calories_list,
      this.quantities_in_grams,
      this.total_calories,

            totalproteinsInGrams,
      totalFibresInGrams,
      totalFatInGrams,
      totalCarbsInGrams,
      mealStringList,
  ];
}

class AutogeneratedMorningSnack {
  final List<MorningSnackModel> results;

  AutogeneratedMorningSnack({this.results});

  factory AutogeneratedMorningSnack.fromJson(Map<String, dynamic> json) {
    List<MorningSnackModel> temp;
    if (json['results'] != null) {
      temp = <MorningSnackModel>[];
      json['results'].forEach((v) {
        temp.add(MorningSnackModel.fromJson(v as Map<String, dynamic>));
      });
    }
    return AutogeneratedMorningSnack(results: temp);
  }

  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    if (results != null) {
      data['results'] = results.map((v) => v.toJson()).toList();
    }
    return data;
  }
}
